name: Expo Deploy App 
on:
  push:
    branches:
      - appstore
jobs:
  publish:
    name: Install and publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPSPECIFIC_PASSWORD }}
      - run: expo upload:ios --non-interactive --config apps/app.generic.json --apple-id ${{ secrets.EXPO_APPLE_ID }} --apple-id-password ${{ secrets.EXPO_APPLE_ID_PASSWORD }}    
