name: Expo Publish Melliodora 3
on:
  push:
    branches:
      - production
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn install
      - run: expo publish --config app.polo_photos.json
      - run: expo publish --config apps/app.generic.json
      - run: expo publish --config apps/app.sais_edu_sg.json
